---
latitude: 40.76479
longitude: -73.97831
map_zoom: 12
name: Viceroy Central Park New York
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 120 W 57th St
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10019'
_hotel_id: VIC363
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
